# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

default: &default
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  auth0_api_audience: <%= ENV['AUTH0_API_AUDIENCE'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>
  auth0_management_api_client_id: <%= ENV['AUTH0_MANAGEMENT_API_CLIENT_ID'] %>
  auth0_management_api_client_secret: <%= ENV['AUTH0_MANAGEMENT_API_CLIENT_SECRET'] %>
  auth0_management_api_audience: <%= ENV['AUTH0_MANAGEMENT_API_AUDIENCE'] %>
  auth0_management_api_origin: <%= ENV['AUTH0_MANAGEMENT_API_ORIGIN'] %>
  sendgrid_api_key: <%= ENV['SENDGRID_API_KEY'] %>
  incentives_portal_origin: <%= ENV['INCENTIVES_PORTAL_ORIGIN'] %>
  bucket_name: <%= ENV['GOOGLE_CLOUD_STORAGE_BUCKET'] %>

development:
  <<: *default
  secret_key_base: 2c0d6d3f2fd258cb3fd51b83400ab760cfbd9637452c09e68863ec5440059e6ace6b5753dd249689a926d587cb91151b6dbbdfe2ea3a7119facbe15752fac074

test:
  <<: *default
  secret_key_base: 278bc3e17e3476502817c57f0f29edacf83b4ab2129d8d4116435d7cccc895e494720f059ae1230cbaf206c8bc2d5a62d31ce9f238345e26f5f4f914e282d5e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
